# Generated by Django 4.1.7 on 2023-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guid', models.CharField(max_length=200)),
                ('guids', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('res', models.CharField(blank=True, max_length=200, null=True)),
                ('hdr', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='tv/posters/')),
                ('bannered_poster', models.ImageField(blank=True, null=True, upload_to='tv/bannered_posters/')),
                ('checked', models.BooleanField()),
                ('blurred', models.BooleanField()),
                ('show_season', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guid', models.CharField(max_length=200)),
                ('guids', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('res', models.CharField(blank=True, max_length=200, null=True)),
                ('hdr', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='films/posters/')),
                ('checked', models.BooleanField()),
                ('bannered_poster', models.ImageField(blank=True, null=True, upload_to='films/bannered_posters/')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plexurl', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('filmslibrary', models.CharField(max_length=200)),
                ('library3d', models.CharField(blank=True, max_length=200, null=True)),
                ('plexpath', models.CharField(blank=True, max_length=200, null=True)),
                ('manualplexpath', models.BooleanField()),
                ('mountedpath', models.CharField(blank=True, max_length=200, null=True)),
                ('t1', models.CharField(blank=True, max_length=200, null=True)),
                ('t2', models.CharField(blank=True, max_length=200, null=True)),
                ('t3', models.CharField(blank=True, max_length=200, null=True)),
                ('t4', models.CharField(blank=True, max_length=200, null=True)),
                ('t5', models.CharField(blank=True, max_length=200, null=True)),
                ('backup', models.BooleanField()),
                ('posters4k', models.BooleanField()),
                ('mini4k', models.BooleanField()),
                ('hdr', models.BooleanField()),
                ('posters3d', models.BooleanField()),
                ('mini3d', models.BooleanField()),
                ('disney', models.BooleanField()),
                ('pixar', models.BooleanField()),
                ('hide4k', models.BooleanField()),
                ('transcode', models.BooleanField()),
                ('tvlibrary', models.CharField(blank=True, max_length=200, null=True)),
                ('tv4kposters', models.BooleanField()),
                ('films4kposters', models.BooleanField()),
                ('tmdb_api', models.CharField(blank=True, max_length=200, null=True)),
                ('tmdb_restore', models.BooleanField()),
                ('recreate_hdr', models.BooleanField()),
                ('new_hdr', models.BooleanField()),
                ('default_poster', models.BooleanField()),
                ('autocollections', models.BooleanField()),
                ('tautulli_server', models.CharField(blank=True, max_length=200, null=True)),
                ('tautulli_api', models.CharField(blank=True, max_length=200, null=True)),
                ('mcu_collection', models.BooleanField()),
                ('tr_r_p_collection', models.BooleanField()),
                ('audio_posters', models.BooleanField()),
                ('loglevel', models.BooleanField()),
                ('manualplexpathfield', models.CharField(blank=True, max_length=200, null=True)),
                ('skip_media_info', models.BooleanField()),
                ('spoilers', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guid', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='seasons/posters/')),
                ('bannered_poster', models.ImageField(blank=True, null=True, upload_to='seasons/bannered_posters/')),
                ('checked', models.BooleanField()),
            ],
        ),
    ]
