# Generated by Django 4.1.7 on 2023-03-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_alter_episode_blurred_alter_episode_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='guid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='guid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
