from django.db import models

# Create your models here.
class Plex(models.Model):
    # plex and docker config
    plexurl = models.CharField(max_length=200)
    token = models.CharField(max_length=200)
    filmslibrary = models.CharField(max_length=200)
    library3d = models.CharField(max_length=200, null=True, blank=True)
    plexpath = models.CharField(max_length=200, null=True, blank=True)
    manualplexpath = models.BooleanField(null=True, blank=True)
    mountedpath = models.CharField(max_length=200, null=True, blank=True)
    # Schedules
    t1 = models.CharField(max_length=200, null=True, blank=True)
    t2 = models.CharField(max_length=200, null=True, blank=True)
    t3 = models.CharField(max_length=200, null=True, blank=True)
    t4 = models.CharField(max_length=200, null=True, blank=True)
    t5 = models.CharField(max_length=200, null=True, blank=True)
    # Enable various settings
    backup = models.BooleanField(null=True, blank=True)
    posters4k = models.BooleanField(null=True, blank=True)
    mini4k = models.BooleanField(null=True, blank=True)
    hdr = models.BooleanField(null=True, blank=True)
    posters3d = models.BooleanField(null=True, blank=True)
    mini3d = models.BooleanField(null=True, blank=True)
    disney = models.BooleanField(null=True, blank=True)
    pixar = models.BooleanField(null=True, blank=True)
    hide4k = models.BooleanField(null=True, blank=True)
    transcode = models.BooleanField(null=True, blank=True)
    tvlibrary = models.CharField(max_length=200, null=True, blank=True)
    tv4kposters = models.BooleanField(null=True, blank=True)
    films4kposters = models.BooleanField(null=True, blank=True)
    tmdb_api = models.CharField(max_length=200, null=True, blank=True)
    tmdb_restore = models.BooleanField(null=True, blank=True)
    recreate_hdr = models.BooleanField(null=True, blank=True)
    new_hdr = models.BooleanField(null=True, blank=True)
    default_poster = models.BooleanField(null=True, blank=True)
    autocollections = models.BooleanField(null=True, blank=True)
    tautulli_server = models.CharField(max_length=200, null=True, blank=True)
    tautulli_api = models.CharField(max_length=200, null=True, blank=True)
    mcu_collection = models.BooleanField(null=True, blank=True)
    tr_r_p_collection = models.BooleanField(null=True, blank=True)
    audio_posters = models.BooleanField(null=True, blank=True)
    loglevel = models.BooleanField(null=True, blank=True)
    manualplexpathfield = models.CharField(max_length=200, null=True, blank=True)
    skip_media_info = models.BooleanField(null=True, blank=True)
    spoilers = models.BooleanField(null=True, blank=True)

class film(models.Model):
    title = models.CharField(max_length=200)
    guid = models.CharField(max_length=200)
    guids = models.CharField(max_length=200)
    size = models.CharField(max_length=200, null=True, blank=True)
    res = models.CharField(max_length=200, null=True, blank=True)
    hdr = models.CharField(max_length=200, null=True, blank=True)
    audio = models.CharField(max_length=200, null=True, blank=True)
    poster = models.ImageField(upload_to='films/posters/', null=True, blank=True)
    checked = models.BooleanField(null=True, blank=True)
    bannered_poster = models.ImageField(upload_to='films/bannered_posters/', null=True, blank=True)
    url= models.CharField(max_length=300, null=True, blank=True)

class episode(models.Model):
    title = models.CharField(max_length=200)
    guid = models.CharField(max_length=200)
    guids = models.CharField(max_length=200)
    size = models.CharField(max_length=200,null=True, blank=True)
    res = models.CharField(max_length=200, null=True, blank=True)
    hdr = models.CharField(max_length=200, null=True, blank=True)
    audio = models.CharField(max_length=200, null=True, blank=True)
    poster = models.ImageField(upload_to='tv/posters/', null=True, blank=True)
    bannered_poster =models.ImageField(upload_to='tv/bannered_posters/', null=True, blank=True)
    checked = models.BooleanField(null=True, blank=True)
    blurred = models.BooleanField(null=True, blank=True)
    show_season = models.CharField(max_length=200, blank=True, null=True)

class season(models.Model):
    title = models.CharField(max_length=200)
    guid = models.CharField(max_length=200)
    poster = models.ImageField(upload_to='seasons/posters/', null=True, blank=True)
    bannered_poster = models.ImageField(upload_to='seasons/bannered_posters/',null=True, blank=True)
    checked = models.BooleanField(null=True, blank=True)
